In [1]:
num1 = 5
num2 = 7

In [2]:
numList = [2, 5, num1, 2, 99, num2]

In [3]:
numList

[2, 5, 5, 2, 99, 7]

In [4]:
num1 = 6

In [5]:
numList

[2, 5, 5, 2, 99, 7]

In [6]:
numList[0]

2

In [7]:
numList[4]

99

In [8]:
#numList[6]

IndexError: list index out of range

In [9]:
len(numList)

6

In [10]:
numList[len(numList) -1]

7

In [11]:
numList[-1]

7

In [12]:
numList

[2, 5, 5, 2, 99, 7]

In [13]:
numList[-3]

2

In [14]:
#numList[-7]

IndexError: list index out of range

In [16]:
# import random

In [22]:
# random.randint(0, 100)

33

In [ ]:
# randNum = random.randint(0, 100)
# if randNum in numList:
#     randNum = random.randint(0, 100)

## List Slice

In [23]:
numList

[2, 5, 5, 2, 99, 7]

In [24]:
numList[1:4] # this does not include the endpoint

[5, 5, 2]

In [25]:
numList[:4]

[2, 5, 5, 2]

In [26]:
numList[1:]

[5, 5, 2, 99, 7]

## Adding to the list

In [27]:
numList.append("random number")

In [28]:
numList

[2, 5, 5, 2, 99, 7, 'random number']

In [29]:
numList[-1]

'random number'

In [30]:
numList.append(numList)

In [31]:
numList[-1]

[2, 5, 5, 2, 99, 7, 'random number', [...]]

In [32]:
numList.insert(1, 3)

In [33]:
numList

[2, 3, 5, 5, 2, 99, 7, 'random number', [...]]

In [34]:
numList.extend(numList)

In [35]:
numList

[2,
 3,
 5,
 5,
 2,
 99,
 7,
 'random number',
 [...],
 2,
 3,
 5,
 5,
 2,
 99,
 7,
 'random number',
 [...]]

In [38]:
secondList = [2, 5, 9]
stringList = ["hi", "python"]

In [39]:
secondList.append(stringList)

In [40]:
secondList

[2, 5, 9, ['hi', 'python']]

In [41]:
secondList[-1]

['hi', 'python']

In [42]:
secondList.extend(stringList)

In [43]:
secondList

[2, 5, 9, ['hi', 'python'], 'hi', 'python']

In [44]:
secondList[-1]

'python'

In [46]:
secondList[-3][-1]

'python'

In [47]:
secondList[3][1]

'python'

## Removing elements from a list

In [48]:
secondList

[2, 5, 9, ['hi', 'python'], 'hi', 'python']

In [49]:
secondList.remove(9) # removes the first occurence of the input

In [50]:
secondList

[2, 5, ['hi', 'python'], 'hi', 'python']

In [51]:
secondList.pop(0) # removes and returns the element and the input index

2

In [52]:
del stringList

In [54]:
#stringList

In [55]:
secondList

[5, ['hi', 'python'], 'hi', 'python']

In [56]:
del secondList[-1]

In [57]:
secondList

[5, ['hi', 'python'], 'hi']

In [58]:
del secondList[:-1]

In [59]:
secondList

['hi']

## Loops
Ways for us to repeat our code

- for
    - Let's us repeat code a fixed amount of times
    - Let's us repeat code directly on elements of lists
- while
    - Let's us repeat code an unknown number of times

In [60]:
numList = [2, 4, 6, 8, 10]

In [61]:
range(10)

range(0, 10)

In [62]:
for num in range(10):
    print(num**2)

0
1
4
9
16
25
36
49
64
81


In [63]:
for num in range(10, 30, 5):
    print(num**2)

100
225
400
625


In [64]:
numList

[2, 4, 6, 8, 10]

In [65]:
len(numList)

5

In [67]:
for asdf in range(len(numList)):
    print(numList[asdf]**2)

4
16
36
64
100


In [69]:
for num in numList:
    print(num**2)
    print("Python is fun")

4
Python is fun
16
Python is fun
36
Python is fun
64
Python is fun
100
Python is fun


In [70]:
while True:
    print("Don't do this at home")

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: 

In [71]:
numList = [2, 5, 7, 2, 5, 9, 0, 2, 4, 7, 1, 0, 100]

In [72]:
while 2 in numList:
    numList.remove(2)
    print(numList)

[5, 7, 2, 5, 9, 0, 2, 4, 7, 1, 0, 100]
[5, 7, 5, 9, 0, 2, 4, 7, 1, 0, 100]
[5, 7, 5, 9, 0, 4, 7, 1, 0, 100]


In [73]:
while 99 in numList:
    numList.remove(99)
    print(numList)

In [74]:
for index, element in enumerate(numList):
    print(index, element)

0 5
1 7
2 5
3 9
4 0
5 4
6 7
7 1
8 0
9 100


## Homework
- Ch.5 Exercises
- Ch. 9 Exercise 6

In [75]:
vec1 = [1, 2, 3]
newVec = []

for num in vec1:
    newVec.append(num**2)
print(newVec)

[1, 4, 9]


In [76]:
matrix = [
    [1, 2, 3],
    [6, 7, 8]
]

In [77]:
matrix[0][1]

2

In [79]:
vec1 = [1, 2, 3]
matrix = [
    [1, 2, 3],
    [6, 7, 8]
]

for num in range(10):
    row = []
    for vec in vec1:
        row.append(vec*num)
    matrix.append(row)
matrix

[[1, 2, 3],
 [6, 7, 8],
 [0, 0, 0],
 [1, 2, 3],
 [2, 4, 6],
 [3, 6, 9],
 [4, 8, 12],
 [5, 10, 15],
 [6, 12, 18],
 [7, 14, 21],
 [8, 16, 24],
 [9, 18, 27]]

In [80]:
import numpy as np

In [81]:
matrix = np.array(matrix)

In [82]:
matrix

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 0,  0,  0],
       [ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18],
       [ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27]])

In [83]:
vec1 = np.array(vec1)

In [84]:
vec1 * 3

array([3, 6, 9])

In [90]:
for i in range(10, 20):
    np.append(matrix, vec1*i, axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [91]:
matrix

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 0,  0,  0],
       [ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18],
       [ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27]])